---

- name: set root password
  mysql_user: name=root password={{ mysql_root_password }} host={{ item }} login_unix_socket=/var/lib/mysql/mysql.sock priv="*.*:ALL,GRANT"
  with_items:
    - "%"
    - ::1
    - 127.0.0.1
    - localhost

- name: remove anonymous mysql users
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ vip }}"
    name: ''
    host: localhost
    state: absent

- name: remove mysql test database
  mysql_db: login_user=root login_password={{ mysql_root_password }}  login_host={{ vip }} name=test state=absent

- name: create e3c_operator user
  mysql_user:
    login_unix_socket: /var/lib/mysql/mysql.sock
    login_host: "{{ vip }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: 'e3c_operator'
    host: "{{ item }}"
    password: "{{ default_password }}"
    priv: "e3c_operator.*:ALL,GRANT"
  with_items:
    - "%"
    - 127.0.0.1
    - ::1
    - "localhost"

