---

- name: config /etc/neutron/neutron.conf for neutron HA
  ini_file:
    path: /etc/neutron/neutron.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: '{{ item.value }}'
  with_items:
    - { section: DEFAULT, option: dhcp_agents_per_network, value: 3 }
    - { section: DEFAULT, option: router_distributed, value: True }
    - { section: DEFAULT, option: l3_ha, value: True }

- name: config /etc/neutron/l3_agent.ini for HA
  ini_file:
    path: /etc/neutron/l3_agent.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: '{{ item.value }}'
  with_items:
    - { section: DEFAULT, option: agent_mode, value: dvr_snat }

- name: config /etc/neutron/plugins/ml2/openvswitch_agent.ini for HA
  ini_file:
    path: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: '{{ item.value }}'
  with_items:
    - { section: agent, option: enable_distributed_routing, value: true }
