---

- name: create neutron resource
  shell: 'pcs resource create {{ item }} systemd:{{ item }} --clone interleave=true op start interval="0" timeout="300s" op stop interval="0" timeout="300s"'
  with_items:
    - neutron-server
    - neutron-openvswitch-agent
    - neutron-dhcp-agent
    - neutron-l3-agent
    - neutron-metadata-agent

- name: wait until neutron resource start
  shell: 'pcs status|grep -A 1 {{ item }}'
  register: result
  retries: 5
  delay: 10
  until: '"Started" in result.stdout'
  with_items:
    - neutron-server
    - neutron-openvswitch-agent
    - neutron-dhcp-agent
    - neutron-l3-agent
    - neutron-metadata-agent

- name: restart haproxy and httpd
  shell: "pcs resource restart {{ item }}"
  with_items:
    - haproxy
    - httpd-clone

