---

- name: restart neutron services
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - neutron-server
    - neutron-openvswitch-agent
    - neutron-dhcp-agent
    - neutron-l3-agent
    - neutron-metadata-agent

