---

- name: cleanup e3c-vpn resource
  shell: 'pcs resource delete {{ item }}'
  with_items:
    - e3c-vpns
  register: result
  failed_when: result.rc != 0 and "does not exist" not in result.stderr

- name: create e3c-vpn resource
  shell: 'pcs resource create e3c-vpns systemd:e3c-vpns op start interval="0" timeout="300s" op stop interval="0" timeout="300s"'

- name: set order for vpn resource
  shell: "pcs constraint order start vip then e3c-vpns kind=Optional"

- name: set constraint for vpn resource
  shell: "pcs constraint colocation add e3c-vpns with vip"

- name: wait until e3c-vpns resource create start
  shell: 'pcs status|grep {{ item }}'
  register: result
  retries: 5
  delay: 10
  until: '"Started" in result.stdout'
  with_items:
    - e3c-vpns

- name: restart vpn resource
  shell: "pcs resource restart e3c-vpns"

- name: wait until openstack start
  shell: 'pcs status|grep {{ item }}'
  register: result
  retries: 5
  delay: 10
  until: '"Started" in result.stdout'
  with_items:
    - e3c-vpns

