---

- name: cleanup vpn resource
  shell: 'pcs resource delete {{ item }}'
  with_items:
    - vpns
  register: result
  failed_when: result.rc != 0 and "does not exist" not in result.stderr

- name: create vpn resource
  shell: 'pcs resource create vpns systemd:vpns op start interval="0" timeout="300s" op stop interval="0" timeout="300s"'

- name: set order for vpn resource
  shell: "pcs constraint order start vip then vpns kind=Optional"

- name: set constraint for vpn resource
  shell: "pcs constraint colocation add vpns with vip"

- name: wait until vpns resource create start
  shell: 'pcs status|grep {{ item }}'
  register: result
  retries: 5
  delay: 10
  until: '"Started" in result.stdout'
  with_items:
    - vpns

- name: restart vpn resource
  shell: "pcs resource restart vpns"

- name: wait until openstack start
  shell: 'pcs status|grep {{ item }}'
  register: result
  retries: 5
  delay: 10
  until: '"Started" in result.stdout'
  with_items:
    - vpns

