---
# gluster config

- name: start necessary services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - glusterd

- name: create /mnt/gfs
  file: path=/mnt/gfs state=directory owner=apache group=apache

- name: create /var/lib/zero/OTC
  file: path={{ item }} state=directory owner=apache group=apache
  with_items:
    - /var/lib/zero/OTC
    - /var/lib/zero/OTC/ISO
    - /var/lib/zero/ISO
    - /var/lib/zero/ISO/ISO

- block:

  - name: probe peer
    gluster_peer: state=present nodes={{ controller_hostname_list }}

  - name: sleep 10s for probe
    shell: sleep 10

  - name: create glusterFS volumes
    gluster_volume:
      name: mygfs
      replicas: 3
      state: present
      bricks: /mnt/gfs
      cluster: "{{ controller_hostname_list }}"
      force: yes
    when: ha_enabled

  - name: create glusterFS volumes
    gluster_volume:
      name: mygfs
      state: present
      bricks: /var/lib/zero/ISO
      cluster: "{{ controller_hostname_list }}"
      force: yes
    when: ha_enabled == False

  - name: sleep 5s for volume create
    shell: sleep 5

  - name: start gluster volume
    gluster_volume:
      state: started
      name: mygfs

  - name: sleep 5s for volume start
    shell: sleep 5

  run_once: true
  delegate_to: "{{ master_node }}"
  when: 'action_type == "install"'

- name: copy configure file for gfs
  copy: src=gfsmount dest=/usr/bin/gfsmount group=root owner=root mode=755

- name: copy gfsmount service file
  copy:
    src: gfsmount.service
    dest: /usr/lib/systemd/system/gfsmount.service

- name: restart gfsmount.service
  systemd:
    name: gfsmount
    daemon_reload: yes
    state: started
    enabled: yes
