---

- name: restart openstack-nova resource
  shell: 'pcs resource restart {{ item }}'
  with_items:
    - openstack-nova-api
    - openstack-nova-scheduler
    - openstack-nova-conductor
    - openstack-nova-novncproxy
    #- openstack-nova-spicehtml5proxy
    - openstack-nova-consoleauth

- name: wait until openstack start
  shell: 'pcs status|grep -A 1 {{ item }}'
  register: result
  retries: 5
  delay: 10
  until: '"Started" in result.stdout'
  with_items:
    - openstack-nova-api
    - openstack-nova-scheduler
    - openstack-nova-conductor
    - openstack-nova-novncproxy
    #- openstack-nova-spicehtml5proxy
    - openstack-nova-consoleauth

- name: restart haproxy and httpd
  shell: "pcs resource restart {{ item }}"
  with_items:
    - haproxy
    - httpd-clone

