---

- name: modify /etc/haproxy/haproxy.cfg
  blockinfile:
    path: /etc/haproxy/haproxy.cfg
    marker: "#{mark} ANSIBLE MANAGED BLOCK FOR CINDER"
    block: |
      listen cinder_api_cluster
          bind {{ controller_vhostname }}:8776
          balance  source
          option  tcpka
          option  httpchk
          option  tcplog
          {% for i in controllers %}
          server {{ i['hostname'] }} {{ i['cluster_ip'] }}:8776 check inter 2000 rise 2 fall 5
          {% endfor %}

