---

- name: copy credential-keys/fernet-keys to other nodes
  copy:
    src: /tmp/{{ item }}/
    dest: /etc/keystone/{{ item }}
  with_items:
    - credential-keys
    - fernet-keys
  when: hostname != master_node

- name: set entries for keystone in haproxy
  blockinfile:
    path: /etc/haproxy/haproxy.cfg
    marker: "#{mark} ANSIBLE MANAGED BLOCK FOR KEYSTONE"
    block: |
        listen keystone_admin_cluster
            bind {{ controller_vhostname }}:35357
            balance  source
            option  tcpka
            option  httpchk
            option  tcplog
            {% for i in controllers %}
            server {{ i['hostname'] }} {{ i['cluster_ip'] }}:35357 check inter 2000 rise 2 fall 5
            {% endfor %}

        listen keystone_public_internal_cluster
            bind {{ controller_vhostname }}:5000
            balance  source
            option  tcpka
            option  httpchk
            option  tcplog
            {% for i in controllers %}
            server {{ i['hostname'] }} {{ i['cluster_ip'] }}:5000 check inter 2000 rise 2 fall 5
            {% endfor %}

