---
# tasks file for database

- name: stop all mysql/mariadb process
  shell: "ps -ef |egrep 'mysql|mariadb'|grep -v grep|awk '{print $2}'|xargs kill -9"
  register: kill_db
  failed_when: kill_db.rc != 0 and kill_db.rc != 123

- name: remove existing mysql package
  yum: name={{ item }} state=absent
  with_items:
    - prefix
    - MariaDB-client
    - MariaDB-Galera-server
    - galera
    - mysql
    - MySQL-python
    - mariadb-config
    - mariadb-server-galera

- name: clean up database and config files
  file: path={{ item }} state=absent
  with_items:
    - /var/lib/mysql/
    - /etc/my.cnf
    - /etc/my.cnf.d/
    - /usr/share/mysql/

- name: install MariaDB with yum
  yum: name={{ item }} state=latest
  with_items:
    - mariadb-server-galera
    - MySQL-python

- name: render wsrep.cnf
  template: src=wsrep.cnf.j2 dest=/etc/my.cnf

- name: add openfile limit in service config
  ini_file: 
    path: /usr/lib/systemd/system/mariadb.service
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: '{{ item.value }}'
  with_items:
    - { section: Service, option: LimitNOFILE, value: 50000 }

- name: reload daemon to ensure config take effect
  systemd:
    daemon_reload: yes

- block:
  - include: "bootstrap.yml"
  
  - include: security.yml
    when: hostname == master_node
  when: 'action_type == "install"'

- block:
  - name: stop mysql service new node
    service: name=mariadb state=stopped

  - name: start mysql with service command
    command: service mariadb start
  when: 'action_type == "recover_controller"'

