---

- name: create sync user
  mysql_user:
    name: '{{ wsrep_sst_username }}'
    host: "{{ item }}"
    password: "{{ wsrep_sst_password }}"
    priv: "*.*:ALL,GRANT"
  with_items:
    - "%"
    - ::1
    - 127.0.0.1
    - "localhost"

- name: create operator user
  mysql_user:
    name: 'operator'
    host: "{{ item }}"
    password: "{{ default_password }}"
    priv: "operator.*:ALL,GRANT"
  with_items:
    - "%"
    - 127.0.0.1
    - ::1
    - "localhost"

- name: create haproxy user
  mysql_user:
    name: haproxy
    host: "{{ item }}"
  with_items:
    - "%"
    - localhost

- name: remove anonymous mysql users
  mysql_user:
     name: ""
     host_all: yes
     state: absent

- name: remove mysql test database
  mysql_db: name=test state=absent

- name: set root password
  mysql_user:
    name: root
    login_user: root
    password: "{{ mysql_root_password }}"
    host: "{{ item }}"
    priv: "*.*:ALL,GRANT"
  with_items:
    - "%"
    - ::1
    - "{{ controller_cluster_ip_list }}"
    - "localhost"
