---

- name: stop packagekit service
  service: name=packagekit state=stopped enabled=no
  register: stop_service
  failed_when: 'stop_service.failed == True and "Could not find the requested service" not in stop_service.msg'

- name: remove packagekit package
  yum: name=PackageKit state=absent

- name: del old repos
  file: path=/etc/yum.repos.d state=absent

- name: ensure repo dir exist
  file: path=/etc/yum.repos.d/ state=directory

- name: copy repo to remote
  copy: src=e3c.repo dest=/etc/yum.repos.d/e3c.repo

- name: clean yum cache
  command: "yum clean all"

- name: clean up transaction
  command: "yum-complete-transaction --cleanup-only"
  ignore_errors: true

