---
# tasks file for init_base

- include: config_yum.yml

- include: system_basic.yml

- include: pip.yml

- name: install needed software
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - openstack-utils
    - openstack-selinux
    - python-openstackclient
    - iftop
    - iperf
    - pyOpenSSL

- name: disable selinux
  selinux: state=disabled

- name: copy qemu-acl rule file
  copy: src=50-qemu-acl.rules dest=/etc/polkit-1/rules.d/

- include: openstack_basic.yml
  when: '"neutron" in my_role or "compute" in my_role'
