---

- name: install openvswitch
  yum: name=openvswitch state=latest
  when: '"neutron" in my_role or "compute" in my_role'

- name: start necessary services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - openvswitch

