---
# tasks file for consul

- name: cleanup consul process
  shell: "ps -ef|grep [c]onsul |awk '{print $2}'|xargs kill"
  register: result
  failed_when: result.rc !=0 and result.rc != 123

- name: copy zip file to remote
  unarchive: src=consul_1.1.0_linux_amd64.zip dest=/usr/bin/

- include: config_consul_mgmt.yml

- include: config_consul_sto.yml
  when: 'sto_ip != None and sto_ip != ""'

- name: start and enble consul-mgmt/consul-sto service only on compute nodes or allinone node
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - consul-mgmt
  when: '["controller"] | intersect(my_role) == [] or ha_enabled == False' 

- name: start and enble consul-sto service only on compute nodes or allinone node
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - consul-sto
  when: '(["controller"] | intersect(my_role) == [] or ha_enabled == False) and (sto_ip != None and sto_ip != "")' 
