# aio
- hosts: localhost
  gather_facts: False
  roles:
    - init_local
  vars_files:
    - default.yml

- hosts: controller
  gather_facts: False
  roles:
    - system_controller
    - gfs
    - single/database
    - single/rabbitmq
    - memcached
    - keystone
    - nova/controller
    - glance
    - mistral
    - cinder
    - consul
    - zabbix/controller
    - cmp/controller
    - lbs
    - docker
    - ceph/controller
    - version
  vars_files:
    - default.yml
    - keys.yml

- hosts: neutron
  gather_facts: False
  roles:
    - system_controller
    - neutron/controller
    - zabbix/compute
    - docker
    - vpn
  vars_files:
    - default.yml
    - keys.yml

- hosts: compute
  gather_facts: False
  roles:
    - nova/compute
    - neutron/compute
    - consul
    - zabbix/compute
    - cmp/compute
    - lbc
    - ceph/compute
    - version
  vars_files:
    - default.yml
    - keys.yml

- hosts: controller
  gather_facts: False
  roles:
    - zabbix_init
    - quota
  vars_files:
    - default.yml
